default: true

extends: null

# 标题级别每次能增加多级
MD001: false

# 标题格式选取最简洁的 ATX 标题样式
MD003:
    style: "atx"

# 无序列表前缀统一使用 -
MD004:
    style: "dash"

# 嵌套列表缩进 2 空格
MD007:
    indent: 2

# 不限制每行字符数
MD013: false

# “兄弟”标题内容不可重复
MD024:
    siblings_only: true

# 允许同一文档中有多个顶级标题
MD025: false

# 有序列表前缀编号依次递增
MD029:
    style: "ordered"

# 列表无需被空白行包围
MD032: false

# 允许使用的 HTML 语法
MD033:
    allowed_elements:
        - br
        - details
        - summary
        - span
        - style

# 水平分割线统一格式
MD035:
    style: "---"

# 统一使用围栏式代码块
MD046:
    style: "fenced"

# 代码块围栏样式为 ``` 
MD048:
    style: "backtick"

# 斜体样式为 *斜体*
MD049:
    style: "asterisk"

# 粗体样式为 **粗体**
MD050:
    style: "asterisk"